### ISSUE TITLE
can we scrub dashes from any resources names and replace with `_`

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-docs-samples#146]
can we scrub dashes from any resources names and replace with `_`

_Originally posted by @rogerthatdev in https://github.com/terraform-google-modules/terraform-docs-samples/pull/143#discussion_r961193127_

**Comment by betsy-lichtenberg** [comment]
I'm working on this

**Comment by betsy-lichtenberg** [comment]
> @bharathkkb san, is there any advantage with this?

It's good to have a convention and follow it for consistency. We also tell customers to use this convention:
https://cloud.google.com/docs/terraform/best-practices-for-terraform#naming-convention

**Comment by msampathkumar** [comment]
Hi, this merge is a one time thing! We need a bot to do this checking for PR's + we need a style guide.

**Comment by msampathkumar** [comment]
Raised a PR: https://github.com/terraform-google-modules/terraform-docs-samples/pull/505
