### ISSUE TITLE
Instead of adding the functions inside of a zip file, could we instead add the files in a sub-directory and then use the `archive_file` terraform resource?

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-docs-samples#147]
Re: `function-source.zip` - instead of adding the functions inside of a zip file, could we instead add the files in a sub-directory and then use the `archive_file` terraform resource? 

For example, move `index.js` and `package.json` to `functions/hello-world/` and then:
```
data "archive_file" "archive" {
  type        = "zip"
  output_path = "/tmp/function-source.zip"
  source_dir  = "functions/hello-world"
}
resource "google_storage_bucket_object" "object" {
  name   = "function-source.zip"
  bucket = google_storage_bucket.bucket.name
  source = data.archive_file.archive.output_path  # Add path to the zipped function source code
}
```

It adds a little more complexity to the sample but could be useful for showing one method of including those functions in source control along side their terraformed cloud function resources.

_Originally posted by @rogerthatdev in https://github.com/terraform-google-modules/terraform-docs-samples/pull/143#discussion_r961199197_

**Comment by bharathkkb** [comment]
Just +1 this as it is a more realistic use case.

**Comment by msampathkumar** [comment]
Update: For `.zip` file, please check  https://github.com/terraform-google-modules/terraform-docs-samples/tree/main/cloudfunctions2_basic
