### ISSUE TITLE
Preferred file format for templates is `.tftpl`

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-docs-samples#148]
Per [Hashicorp documentation](https://www.terraform.io/language/functions/templatefile) the preferred file format for templates is `.tftpl`  

That will help avoid any confusion re: the double $'s

_Originally posted by @rogerthatdev in https://github.com/terraform-google-modules/terraform-docs-samples/pull/143#discussion_r961200566_

**Comment by rogerthatdev** [comment]
File in question: [`eventarc_workflows/workflow.yaml`](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/eventarc_workflows/workflow.yaml)

**Comment by bharathkkb** [comment]
https://cloud.google.com/docs/terraform/best-practices-for-terraform#static-files

**Comment by glasnt** [comment]
This appears to have been addressed as part of #350. 

As of now, there doesn't appear template files in use in this repo, so nothing left to change.
