### ISSUE TITLE
Periodic Test: Looker Instance Qutoa

### ISSUE THREAD

**Issue by apeabody** [terraform-google-modules/terraform-docs-samples#610]
### TL;DR

The Periodic Test is failing on a Looker Instance Qutoa:

`Error creating Instance: googleapi: Error 429: Quota limit 'StandardInstancesPerProjectPerRegion' has been exceeded. Limit: 0 in region us-central1.`

Ref: https://github.com/terraform-google-modules/terraform-docs-samples/issues/609

### Terraform Configuration

```hcl
CI
```

### Terraform Version

```sh
CI
```

**Comment by glasnt** [comment]
Resolved in #620
