### ISSUE TITLE
Adding "idle-timeout-seconds" terraform variable in for vertex_workbench_notebook pipeline

### ISSUE THREAD

**Issue by itopuz-clgx** [terraform-google-modules/terraform-docs-samples#611]
### TL;DR

Hello,

We wuld like to add new terraform variable (idle-timeout-seconds) to control idle vertex ai notebooks for vertex_workbench_notebook. Probably needs to be added into "vertex.tf"
Could you please help us ?
Thanks,
İmran

### Terraform Resources

```markdown
https://cloud.google.com/vertex-ai/docs/workbench/instances/idle-shutdown
https://github.com/terraform-google-modules/terraform-docs-samples/blob/HEAD/vertex_ai/workbench_idle_shutdown/main.tf
```

**Comment by glasnt** [comment]
As of 5.17.0, [google_notebook_instance is deprecated](https://registry.terraform.io/providers/hashicorp/google/5.17.0/docs/resources/notebooks_instance), and the docs suggest using google_workbench_instance instead. As you linked, this resource already includes the idle-timeout option you are after.
